### ISSUE TITLE
Screwdriver rotates blocks

### ISSUE THREAD

**Issue by CubeWrench202** [CubeWrench202/PowerRed#5]

**Comment by master801** [comment]
What do you mean by this?

Should it only rotate the power red machines or everything that can be rotated?

**Comment by CubeWrench202** [comment]
PowerRed machines, future gates, vanilla redstone devices(pistons,dispensers,etc).

**Comment by master801** [comment]
@CubeWrench202 So pretty much everything, am I correct?

**Comment by CubeWrench202** [comment]
If we do the pistons and the breaker for now is OK actually, i just care to get it working :P

**Comment by master801** [comment]
@CubeWrench202 Ha-ha, okay.

**Comment by master801** [comment]
Commit 2c3b8bf improves the previous implementation.
